#!/bin/bash
#SBATCH --job-name=tilted.fermion
#SBATCH --output=output_run1/fermion.%a.%A.out
#SBATCH --error=output_run1/fermion.%a.%A.err
#SBATCH --time=4-00:00:00
#SBATCH --nodes=5
#SBATCH --mem-per-cpu=100M
#SBATCH --ntasks=200
#SBATCH --mem-per-cpu=3000MB
#SBATCH --cpus-per-task=1

module load conda

dirname=(`python mkdir.py`)

echo "========= Job started  at `date` on `hostname -s` =========="

for num in {0..199}

do
srun --ntasks=1 python main.py ${dirname}
done

wait

echo "========= Job finished at `date` =========="
