#!/bin/bash
#SBATCH -N 1
#SBATCH --error=fermion.%J.err
#SBATCH --output=fermion.%J.out
#SBATCH --mail-user=fizaan.khan.phy21@iitbhu.ac.in
#SBATCH --job-name=deo.double.jee
#SBATCH --ntasks-per-node=40

module load conda

echo echo