#!/bin/bash
#SBATCH --job-name=tilted.fermion
#SBATCH --output=output_run1/fermion.out
#SBATCH --error=output_run1/fermion.err
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=40
#SBATCH --mem-per-cpu=4800M
#SBATCH --array=1-10%10
#SBATCH --export=NONE

echo "========= Job started  at `date` on `hostname -s` =========="

export OMP_NUM_THREADS=1

echo "Array job id : $SLURM_ARRAY_JOB_ID"
echo "Job id       : $SLURM_JOB_ID"
echo "Array task id: $SLURM_ARRAY_TASK_ID"

module load conda

dirname=(`python mkdir.py`)

runstring=(`echo ${SLURM_ARRAY_TASK_ID:-1}`)
echo "Track-ID: ${runstring[0]}"

python main.py ${dirname} ${runstring[*]} &
wait $!

echo "========= Job finished at `date` =========="
