#!/bin/bash
#SBATCH --nodes=2                        # Number of nodes
#SBATCH --ntasks-per-node=1               # Number of tasks per node
#SBATCH --cpus-per-task=40                 # Number of CPU cores per task
#SBATCH --time=4-00:00:00                   # Walltime
#SBATCH --mem-per-cpu=4800M
#SBATCH --error=fermion.%J.err
#SBATCH --output=fermion.%J.out
#SBATCH --mail-user=fizaan.khan.phy21@iitbhu.ac.in
#SBATCH --job-name=tilted.fermion

module load conda

source activate hpc-env

python main.py